version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "764744153968"
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "test-coworking-analytics"
    CODEBUILD_BUILD_NUMBER: "latest"
    DB_USERNAME: "myuser"
    DB_PASSWORD: "mypassword"
phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Starting build at $(date)"
      - echo "Building the Docker image..."
      - docker build -f Dockerfile -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER ./analytics
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo "Completed build at $(date)"
      - echo "Pushing the Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
